name = "infer-type-challenges"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]

[dev]
ip = "0.0.0.0"
port = 3000

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[env.dev.vars]
database_name = "dev"
database_id = "dev"

[env.prd.vars]
database_name = "prd"
database_id = "prd"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "database_name"
database_id = "database_id"

# [ai]
# binding = "AI"
